### ISSUE TITLE
problems to use the app

### ISSUE THREAD

**Issue by agnespinhanelli** [HaikuTeam/core#3]
I just created my account, downloaded the app but I can't log in. Apparently t's not the password or the email that is wrong or anything like that, but it keeps showing just an "Uncategorized Error" message, so I don't really know, no feedbacks. 

<img width="396" alt="screen shot 2018-02-19 at 11 42 57" src="https://user-images.githubusercontent.com/29760496/36383154-0f95d3c8-156a-11e8-81fc-44984a97abe5.png">

**Comment by zackbrown** [comment]
Hey @agnespinhanelli I see you closed this, so I'm guessing you got around the issue (this was probably
 due to email verification) —

Just for posterity: there was a bug in the login UI that shipped with our last release.  This screen is supposed to show a more informative error, inviting you to verify your email (and/or to re-send the verification email.)  This is now fixed in master and will roll out with our next release.
